#pragma once

#include "modules/board/board.h"
#include "modules/break/break.h"
#include "modules/cpu/cpu.h"
#include "modules/command/command.h"
#include "modules/colors/colors.h"
#include "modules/custom/custom.h"
#include "modules/datetime/datetime.h"
#include "modules/disk/disk.h"
#include "modules/kernel/kernel.h"
#include "modules/loadavg/loadavg.h"
#include "modules/memory/memory.h"
#include "modules/os/os.h"
#include "modules/packages/packages.h"
#include "modules/separator/separator.h"
#include "modules/title/title.h"
#include "modules/uptime/uptime.h"
