#pragma once

// For "fastfetch.h"

#include "modules/board/option.h"
#include "modules/break/option.h"
#include "modules/cpu/option.h"
#include "modules/colors/option.h"
#include "modules/custom/option.h"
#include "modules/command/option.h"
#include "modules/datetime/option.h"
#include "modules/disk/option.h"
#include "modules/kernel/option.h"
#include "modules/loadavg/option.h"
#include "modules/memory/option.h"
#include "modules/os/option.h"
#include "modules/packages/option.h"
#include "modules/separator/option.h"
#include "modules/title/option.h"
#include "modules/uptime/option.h"
